In [9]:
import pandas as pd
rating = pd.read_csv('data_raw/lastfm/user_artists_ratings.csv', names=['user_id', 'item_id', 'rating', 'timestamp', 'tag_id', 'weight'],
                          sep=",", engine='python')

In [10]:
rating

user_id  item_id  rating      timestamp  tag_id  weight
0            2       52       5  1238536800000      13   11690
1            2       52       5  1238536800000      15   11690
2            2       52       5  1238536800000      18   11690
3            2       52       5  1238536800000      21   11690
4            2       52       5  1238536800000      41   11690
...        ...      ...     ...            ...     ...     ...
73353     2100    16437       4  1277935200000       4     443
73354     2100    16437       4  1272664800000     292     443
73355     2100    16437       4  1277935200000    2087     443
73356     2100    16437       4  1272664800000    2801     443
73357     2100    16437       4  1277935200000    3335     443

[73358 rows x 6 columns]

In [18]:
rating2 = rating.drop_duplicates(['user_id','item_id','rating']).reset_index()

In [25]:
rating3 = rating2.drop(columns=['index'])
rating3

user_id  item_id  rating      timestamp  tag_id  weight
0            2       52       5  1238536800000      13   11690
1            2       63       5  1238536800000      13    3735
2            2       73       5  1238536800000      13    2584
3            2       94       5  1238536800000      13    1373
4            2       96       5  1238536800000      19    1342
...        ...      ...     ...            ...     ...     ...
20660     2100     1111       5  1235862000000     574    1062
20661     2100     6658       4  1254348000000       4     731
20662     2100     8322       4  1241128800000       4     650
20663     2100    13978       4  1243807200000     574     535
20664     2100    16437       4  1277935200000       4     443

[20665 rows x 6 columns]

In [49]:
rating4 = rating3.groupby('user_id')['item_id'].filter(lambda x: len(x) >= 10)

In [51]:
counts = rating3['user_id'].value_counts()

In [52]:
counts

1584    50
1895    50
12      50
66      50
625     50
        ..
2011     1
1915     1
1867     1
82       1
2057     1
Name: user_id, Length: 1824, dtype: int64

In [53]:
counts[counts >= 10]

1584    50
1895    50
12      50
66      50
625     50
        ..
1503    10
1189    10
172     10
689     10
1465    10
Name: user_id, Length: 665, dtype: int64

In [57]:
rating4 = rating3[rating3['user_id'].isin(counts[counts>=10].index)].reset_index()
rating5 = rating4.drop(columns=['index'])
rating5

user_id  item_id  rating      timestamp  tag_id  weight
0            4       51       3  1196463600000      16     228
1            4       53       4  1191189600000      18     686
2            4       64       4  1180648800000      13     420
3            4       70       4  1191189600000      18     389
4            4       72       5  1180648800000      18    4983
...        ...      ...     ...            ...     ...     ...
16470     2099    18717       2  1264978800000      13     132
16471     2099    18719       2  1264978800000     758     118
16472     2099    18721       2  1230764400000      15     108
16473     2099    18723       2  1288566000000     626      87
16474     2099    18724       2  1264978800000      13      84

[16475 rows x 6 columns]

In [58]:
rating5.to_csv(r'data_raw/lastfm/user_artists_ratings.csv',header=None, index=False)

In [59]:
import pandas as pd
rating = pd.read_csv('data_raw/lastfm/user_artists_ratings.csv', names=['user_id', 'item_id', 'rating', 'timestamp', 'tag_id', 'weight'],
                          sep=",", engine='python')
rating

user_id  item_id  rating      timestamp  tag_id  weight
0            4       51       3  1196463600000      16     228
1            4       53       4  1191189600000      18     686
2            4       64       4  1180648800000      13     420
3            4       70       4  1191189600000      18     389
4            4       72       5  1180648800000      18    4983
...        ...      ...     ...            ...     ...     ...
16470     2099    18717       2  1264978800000      13     132
16471     2099    18719       2  1264978800000     758     118
16472     2099    18721       2  1230764400000      15     108
16473     2099    18723       2  1288566000000     626      87
16474     2099    18724       2  1264978800000      13      84

[16475 rows x 6 columns]

In [1]:
!rm -r 'data_processed/lastfm/'

In [2]:
!python3 prepareDataset.py

start time 1957-03-01 07:00:00, split_time 2010-08-01 06:00:00, end time 2011-05-09 19:44:57.425000
100%|████████████████████████████████████████| 665/665 [00:00<00:00, 891.96it/s]
num warm users: 599, num cold users: 66
min count: 10, avg count: 24, max count: 50
100%|█████████████████████████████████████| 2575/2575 [00:01<00:00, 1856.86it/s]
num warm items: 99,   num cold items: 2476
min count: 1,  avg count: 6,  max count: 68
100%|████████████████████████████████████████| 665/665 [00:01<00:00, 400.68it/s]


In [3]:
from mamoRec import *

In [4]:
model = MAMRec('lastfm') 
outputs = model.test()

len_user
665
training_size
532
train_users
532
test_users
132
x1.size
torch.Size([1, 1892])
friend_idx.size
torch.Size([1, 1892])
friend_emb.size
torch.Size([1, 100])
friend_emb.size end
tensor([0.4859, 0.2838, 0.2303], grad_fn=<SoftmaxBackward>)
tensor([[0.4859],
        [0.2838],
        [0.2303]], grad_fn=<ViewBackward>)
user_id
539
sup_x1
torch.Size([9, 1892])
sup_x2
torch.Size([9, 60])
sup_y
torch.Size([9])
sup_y0
torch.Size([9])
que_x1
torch.Size([1, 1892])
que_x2
torch.Size([0])
que_y
torch.Size([1])
que_y0
torch.Size([0])
x1.size
torch.Size([5, 1892])
friend_idx.size
torch.Size([5, 1892])
friend_emb.size
torch.Size([5, 100])
friend_emb.size end
x2.size
torch.Size([5, 60])
category_idx.size
torch.Size([5, 60])
category_emb.size
torch.Size([5, 100])
x1
tensor([[-1.1047e-02, -4.9718e-03, -1.9517e-02,  1.6309e-01,  3.0495e-02,
          1.2716e-01,  2.1328e-01,  7.8488e-02, -1.9074e-02,  2.0964e-02,
         -2.9807e-03, -1.0563e-02,  2.2762e-02, -3.9043e-03, -1.8256e-03,
         

/opt/anaconda3/lib/python3.8/site-packages/torch/nn/functional.py:1625: UserWarning: nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.
  warnings.warn("nn.functional.sigmoid is deprecated. Use torch.sigmoid instead.")
/Users/kennethcheng/MSBD5002_Project/Code-for-MAMO/modules/memories.py:81: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  attention_values = self.soft_max_layer(fc_layers)
/opt/anaconda3/lib/python3.8/site-packages/torch/nn/modules/container.py:117: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  input = module(input)


IndexError: too many indices for tensor of dimension 1

In [26]:
outputs

[(tensor([[1., 0., 0., 0., 0.],
          [1., 0., 0., 0., 0.],
          [1., 0., 0., 0., 0.]], grad_fn=<SoftmaxBackward>),
  tensor([0, 0, 0]),
  tensor([4, 4, 4]),
  tensor(1.9048, grad_fn=<NllLossBackward>),
  tensor(4.),
  1.0,
  tensor([[0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0],
          [0, 0, 0,  ..., 0, 0, 0]]),
  tensor([[1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
           0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0,
           0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0],
          [1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
           0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0,
           0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0],
          [1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0,
           0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0,
           0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0]])),
 (tensor([[1

In [6]:
# Average Loss
loss_val = 0
for i in range(0,len(outputs)):
    loss_val += float(outputs[i][3])
loss_per_user = loss_val/len(outputs)
loss_per_user

1.8009362576843857

In [7]:
# Average MAE
mae_val = 0
for i in range(0,len(outputs)):
    mae_val += float(outputs[i][4])
mae_per_user = mae_val/len(outputs)
mae_per_user

2.705627707111371

In [8]:
# Average NDCG
ndcg_val = 0
for i in range(0,len(outputs)):
    ndcg_val += float(outputs[i][5])
ndcg_per_user = ndcg_val/len(outputs)
ndcg_per_user

1.0

In [25]:
# Rating
i = 150
outputs[i][1]

tensor([0, 0, 0])